# Generated by Django 4.2.7 on 2023-12-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attachment',
            field=models.ManyToManyField(blank=True, to='post.postattachment'),
        ),
    ]
