# Generated by Django 4.2.7 on 2023-12-06 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_post_comments_count_comment_post_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created_at',)},
        ),
    ]
