# Generated by Django 4.2.7 on 2023-12-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_trend'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
