# Generated by Django 4.2.7 on 2023-12-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_friendshiprequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendshiprequest',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='sent', max_length=20),
        ),
    ]
