# Generated by Django 4.2.7 on 2023-12-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_friendshiprequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendshiprequest',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('sent', 'Sent'), ('rejected', 'Rejected')], default='sent', max_length=20),
        ),
    ]
