# Generated by Django 4.2.7 on 2023-12-07 17:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_friendshiprequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='people_may_you_know',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendshiprequest',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('sent', 'Sent')], default='sent', max_length=20),
        ),
    ]
