# Generated by Django 4.2.7 on 2023-12-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_user_people_may_you_know_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendshiprequest',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='sent', max_length=20),
        ),
    ]
